"""
Visual regression capture for new cBioPortal — study_view page.
Generated by /visual-regression from progress/STUDY_VIEW_GAPS.md.

Captures screenshots of implemented features on the local reimplementation
for side-by-side comparison with the legacy cbioportal.org.

Run:
    uv run python tests/visual/capture_new_study_view.py
    uv run python tests/visual/capture_new_study_view.py --headed
    uv run python tests/visual/capture_new_study_view.py --port 8001
"""
from __future__ import annotations

import argparse
import os
from pathlib import Path

from playwright.sync_api import sync_playwright, Page

LOAD_TIMEOUT_MS = 30_000
SETTLE_MS = 5_000

OUT_DIR = Path(__file__).parent / "screenshots" / "new"


def wait_for_dashboard(page: Page) -> None:
    """Wait for JS to build the dynamic dashboard widgets and charts to render."""
    try:
        page.wait_for_load_state("networkidle", timeout=LOAD_TIMEOUT_MS)
    except Exception:
        pass
    # Wait for dynamic widgets to be created by buildDashboard() JS
    try:
        page.wait_for_selector("#widget-CANCER_TYPE", timeout=15_000)
    except Exception:
        pass
    page.wait_for_timeout(SETTLE_MS)


def capture_full_dashboard(page: Page, study_id: str) -> None:
    """Full-page screenshot of the study view dashboard."""
    print("  [1/7] Full dashboard")
    page.screenshot(path=str(OUT_DIR / "full_dashboard.png"), full_page=True)


def capture_chart_priority_layout(page: Page, study_id: str) -> None:
    """Screenshot the chart grid area to verify chart ordering."""
    print("  [2/7] Chart priority layout")
    # Full-page captures the entire grid layout; element screenshot can timeout on large grids
    page.screenshot(path=str(OUT_DIR / "chart_priority_layout.png"), full_page=True)


def capture_pie_chart_center_labels(page: Page, study_id: str) -> None:
    """Screenshot a pie chart to verify center count label."""
    print("  [3/7] Pie chart center labels")
    for attr in ["OS_STATUS", "GENDER", "SEX", "SAMPLE_TYPE"]:
        widget = page.locator(f"#widget-{attr}").first
        if widget.count() > 0:
            widget.screenshot(path=str(OUT_DIR / "pie_chart_center_labels.png"))
            return
    print("    WARNING: no pie chart widget found")


def capture_pubmed_link(page: Page, study_id: str) -> None:
    """Screenshot the study header area showing the PubMed link."""
    print("  [4/7] PubMed link in header")
    header = page.locator(".study-view-header, .study-header-top").first
    if header.count() > 0:
        header.screenshot(path=str(OUT_DIR / "pubmed_link.png"))
    else:
        page.screenshot(path=str(OUT_DIR / "pubmed_link.png"), clip={"x": 0, "y": 0, "width": 1600, "height": 200})


def capture_study_help_link(page: Page, study_id: str) -> None:
    """Screenshot the toolbar area where 'Study Page Help' link should appear."""
    print("  [5/7] Study help link / toolbar")
    page.screenshot(path=str(OUT_DIR / "study_help_link.png"), clip={"x": 0, "y": 0, "width": 1600, "height": 300})


def capture_numeric_histogram(page: Page, study_id: str) -> None:
    """Screenshot a numeric clinical attribute chart (AGE / CURRENT_AGE_DEID)."""
    print("  [6/7] Numeric histogram (age)")
    for attr in ["CURRENT_AGE_DEID", "AGE", "DIAGNOSIS_AGE", "AGE_AT_DIAGNOSIS"]:
        widget = page.locator(f"#widget-{attr}").first
        if widget.count() > 0:
            widget.screenshot(path=str(OUT_DIR / "numeric_histogram.png"))
            return
    print("    WARNING: no age/numeric widget found")


def capture_cna_gene_filter(page: Page, study_id: str) -> None:
    """Click a gene in the CNA table and screenshot the filtered dashboard."""
    print("  [7/7] CNA gene filter interaction")
    cna_widget = page.locator("#widget-_cna_genes").first
    if cna_widget.count() == 0:
        print("    WARNING: CNA genes widget not found")
        return

    cna_widget.screenshot(path=str(OUT_DIR / "cna_table_unfiltered.png"))

    # Click the first gene row to apply a filter
    try:
        row = page.locator("#table-body-_cna_genes tr").first
        checkbox = row.locator(".cbio-table-checkbox").first
        if checkbox.count() > 0:
            checkbox.click(force=True)
        else:
            row.click(force=True)
        page.wait_for_timeout(3_000)
        try:
            page.wait_for_load_state("networkidle", timeout=10_000)
        except Exception:
            pass
        page.screenshot(path=str(OUT_DIR / "cna_gene_filter_applied.png"), full_page=True)
    except Exception as e:
        print(f"    WARNING: could not apply CNA filter: {e}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Visual regression: new cBioPortal study view")
    parser.add_argument("--study", default="msk_chord_2024")
    parser.add_argument("--headed", action="store_true")
    parser.add_argument("--port", default=os.environ.get("CBIO_PORT", "8000"))
    args = parser.parse_args()

    base_url = f"http://localhost:{args.port}"
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    study_url = f"{base_url}/study/summary?id={args.study}"
    print(f"\nCapturing new study view: {study_url}")

    with sync_playwright() as p:
        browser = p.chromium.launch(
            headless=not args.headed,
            slow_mo=50,
            args=["--ignore-certificate-errors"],
        )
        context = browser.new_context(
            viewport={"width": 1600, "height": 900},
            ignore_https_errors=True,
        )
        page = context.new_page()

        print(f"  Navigating to {study_url}")
        page.goto(study_url, timeout=LOAD_TIMEOUT_MS)
        wait_for_dashboard(page)

        capture_full_dashboard(page, args.study)
        capture_chart_priority_layout(page, args.study)
        capture_pie_chart_center_labels(page, args.study)
        capture_pubmed_link(page, args.study)
        capture_study_help_link(page, args.study)
        capture_numeric_histogram(page, args.study)
        capture_cna_gene_filter(page, args.study)

        browser.close()

    print(f"\nDone. Screenshots saved to {OUT_DIR}")
    for f in sorted(OUT_DIR.glob("*.png")):
        print(f"  {f.name}")


if __name__ == "__main__":
    main()
